sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t test -f dockerfile.dev ./

script:
  - docker run -e CI=true test npm run test -- --coverage

after_success:
  - echo "Test Success!"
