version: "3"
services:
  react:
    build: ./

    ports:
      - "3000:80"
    # volumes:
    #   - /usr/src/app/node_modules
    #   - ./:/usr/src/app
    stdin_open: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    restart: always
#   test:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     volumes:
#       - /usr/src/app/node_modules
#       - ./:/usr/src/app
#     command: ["npm", "run", "test"]
